### ISSUE TITLE
unable to run the code with missing files

### ISSUE THREAD

**Issue by mrmrfan** [yunshengb/SimGNN#1]
Hello. Thank you for sharing this work!

Recently, I read the README file and do as what it tells me to do. But I've got some problems when I try to run the code by `python main.py`. 

Traceback (most recent call last):
  File "D:/SimGNN/SimGNN-master/model/Siamese/main.py", line 48, in <module>
    main()
  File "D:/SimGNN/SimGNN-master/model/Siamese/main.py", line 36, in main
    eval = Eval(data, dist_calculator)
  File "D:\SimGNN\SimGNN-master\model\Siamese\eval.py", line 25, in __init__
    row_graphs=test_gs1, col_graphs=test_gs2)
  File "D:\SimGNN\SimGNN-master\model\Siamese/../../src\results.py", line 497, in load_results_as_dict
AIDS700nefData_test loaded from D:\SimGNN\SimGNN-master/save/AIDS700nefData_test with 140 graphs
AIDS700nefData_train loaded from D:\SimGNN\SimGNN-master/save/AIDS700nefData_train with 560 graphs
    time_mat=time_mat, model_info=model_info)
  File "D:\SimGNN\SimGNN-master\model\Siamese/../../src\results.py", line 506, in load_result
    dataset, model, dist_mat, row_graphs, col_graphs)
  File "D:\SimGNN\SimGNN-master\model\Siamese/../../src\results.py", line 162, in __init__
    self.dist_metric(), self.model_, len(row_graphs), len(col_graphs))
  File "D:\SimGNN\SimGNN-master\model\Siamese/../../src\results.py", line 238, in _load_result_mat
    raise RuntimeError('No results found {}'.format(file_p))
RuntimeError: No results found D:\SimGNN\SimGNN-master/result/aids700nef/ged/ged_ged_mat_aids700nef_beam1_*.npy

It seems that the file `/result/aids700nef/ged/ged_ged_mat_aids700nef_beam1_*.npy` is missing. 

But I don't  figure out the right code to produce this file.

**Comment by yunshengb** [comment]
Please download and extract the result files under `/result` from https://drive.google.com/drive/folders/1UXEGozaThjjuC-hnt4C7jn06L6I2Ra1v?usp=sharing

Thanks!

**Comment by mrmrfan** [comment]
Thank you！
