### ISSUE TITLE
Got "marker" error when running main.py

### ISSUE THREAD

**Issue by kxhit** [yunshengb/SimGNN#10]
Hi! @yunshengb  Thanks for your code!

I run main.py and got error at test().  Could you help me? Thanks!!!
Logs:

graph embedding 0.88906
[ 0.10863562  0.08224115 -0.00754932  0.06741448  0.16102181  0.00956849
  0.12104003 -0.01132082  0.17263308 -0.08167651 -0.04887944  0.00461488
 -0.02077552 -0.11411279  0.00751702 -0.03882935]
Evaluating...
Saved to /media/work/3D/SimGNN/baiyunshen/SimGNN/result/aids700nef/mse/ged_mse_aids700nef_astar_beam1_beam2_beam5_beam10_beam20_beam40_beam80_hungarian_vj_siamese_regression_norm.png
Saved to /media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/logs/siamese_regression_aids700nef_2019-08-30T01:22:40/ged_mse_aids700nef_astar_beam1_beam2_beam5_beam10_beam20_beam40_beam80_hungarian_vj_siamese_regression_norm.png
Saved to /media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/logs/siamese_regression_aids700nef_2019-08-30T01:22:40/ged_mse_aids700nef_astar_beam1_beam2_beam5_beam10_beam20_beam40_beam80_hungarian_vj_siamese_regression_norm.eps
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/markers.py", line 248, in set_marker
    Path(marker)
  File "/usr/lib/python3/dist-packages/matplotlib/path.py", line 137, in __init__
    vertices = np.asarray(vertices, np.float_)
  File "/home/kx/venv/lib/python3.5/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'X'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/main.py", line 44, in <module>
    main()
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/main.py", line 36, in main
    test(data, eval, model, saver, sess, val_results_dict)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/train.py", line 71, in test
    model.get_eval_metrics_for_test(), saver)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/eval.py", line 92, in eval_for_test
    eps_dir)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/eval.py", line 156, in _eval
    self.norms, plot, eps_dir=eps_dir)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 351, in plot_preck
    False, plot_results, eps_dir)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 381, in plot_preck_helper
    **get_plotting_arg(args2, model))
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 3251, in scatter
    edgecolors=edgecolors, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 1814, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 3877, in scatter
    marker_obj = mmarkers.MarkerStyle(marker)
  File "/usr/lib/python3/dist-packages/matplotlib/markers.py", line 171, in __init__
    self.set_marker(marker)
  File "/usr/lib/python3/dist-packages/matplotlib/markers.py", line 252, in set_marker
    ' {0}'.format(marker))
ValueError: Unrecognized marker style X

**Comment by kxhit** [comment]
Maybe the matplotlib version. Solved by changing "X" -> "x", "P" ->"p".

**Comment by kxhit** [comment]
New error occurred.

AIDS700nefData_test loaded from /media/work/3D/SimGNN/baiyunshen/SimGNN/save/AIDS700nefData_test with 140 graphs
/media/work/3D/SimGNN/baiyunshen/SimGNN/result/aids700nef/ged/ged_ged_mat_aids700nef_astar_2018-06-27T19:38:42_qilin_10cpus.npy
/media/work/3D/SimGNN/baiyunshen/SimGNN/result/aids700nef/time/ged_time_mat_aids700nef_astar_2018-06-27T19:38:42_qilin_10cpus.npy
Traceback (most recent call last):
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/main.py", line 44, in <module>
    main()
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/main.py", line 36, in main
    test(data, eval, model, saver, sess, val_results_dict)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/train.py", line 71, in test
    model.get_eval_metrics_for_test(), saver)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/eval.py", line 92, in eval_for_test
    eps_dir)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/eval.py", line 116, in _eval
    rs[FLAGS.model], eps_dir + '/gt_rk')
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 1439, in comb_gt_rk
    gs_rank = gs_rank + [train_data.graphs[j] for j in gids_rank]
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 1439, in <listcomp>
    gs_rank = gs_rank + [train_data.graphs[j] for j in gids_rank]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by kxhit** [comment]
Solved by changing "j" -> "int(j)"

**Comment by kxhit** [comment]
Got new errors.

AIDS700nefData_test loaded from /media/work/3D/SimGNN/baiyunshen/SimGNN/save/AIDS700nefData_test with 140 graphs
/media/work/3D/SimGNN/baiyunshen/SimGNN/result/aids700nef/ged/ged_ged_mat_aids700nef_astar_2018-06-27T19:38:42_qilin_10cpus.npy
/media/work/3D/SimGNN/baiyunshen/SimGNN/result/aids700nef/time/ged_time_mat_aids700nef_astar_2018-06-27T19:38:42_qilin_10cpus.npy
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main()
  File "main.py", line 36, in main
    test(data, eval, model, saver, sess, val_results_dict)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/train.py", line 71, in test
    model.get_eval_metrics_for_test(), saver)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/eval.py", line 92, in eval_for_test
    eps_dir)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/eval.py", line 116, in _eval
    rs[FLAGS.model], eps_dir + '/gt_rk')
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 1454, in comb_gt_rk
    [get_text_label_small(r, i, j, norm, False, dataset, gids_groundtruth) for j in gids_groundtruth]
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 1454, in <listcomp>
    [get_text_label_small(r, i, j, norm, False, dataset, gids_groundtruth) for j in gids_groundtruth]
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 1138, in get_text_label_small
    ged_str = get_ged_select_norm_str(r, qid, gid, norm)
  File "/media/work/3D/SimGNN/baiyunshen/SimGNN/model/Siamese/../../src/exp.py", line 770, in get_ged_select_norm_str
    return '{:.2f}({})'.format(norm_ged, int(ged))
TypeError: non-empty format string passed to object.__format__
